spring.application.name=gestorFinance

server.port=8071

spring.datasource.url=jdbc:postgresql://localhost:5432/gestorFinanzas
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true